In [1]:
# We will do the imports required for this notebook here

# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm

# use timeit to benchmark some methods
from timeit import default_timer as timer

# ansitable is a great package for printing tables in a terminal
from ansitable import ANSITable

## Definição do manipulador ABB IRB 460

In [11]:
#tamanho dos elos ativos
l1 = 0.2345
l2 = 0.508
l3 = 0.260
l4 = 0.945
l5 = 1.025
l6 = 0.220
l7 = -0.2515

E1 = rtb.ET.tx(l3)     #0_1
E2 = rtb.ET.tz(l2)     #0_1
E3 = rtb.ET.tx(l3)     #0_1
E4 = rtb.ET.tz(l2)     #1_3
E5 = rtb.ET.tz(l4)     #2_4
E6 = rtb.ET.tx(-0.400) #3_p1
E7 = rtb.ET.Ry()       #reset p1_0
E8 = rtb.ET.tz(l4)     #p1_p2
E9 = rtb.ET.tx(l5)     #4_5
E10 = rtb.ET.Ry()      #1_p3 
E11 = rtb.ET.tx(-l3)   #1_p3 
E12 = rtb.ET.tz(0.437) #1_p3 
E13 = rtb.ET.tx(0.247) #p3_p4 
E14 = rtb.ET.tz(0.804) #p3_p4
E15 = rtb.ET.Ry()      #reset 3_0 
E16 = rtb.ET.tx(0.04884)#3_p5
E17 = rtb.ET.tz(-0.6488)#3_p5
E18 = rtb.ET.Ry()       #reset p5_0
E19 = rtb.ET.tx(-0.0350)#p5_p6
E20 = rtb.ET.tz(0.33367)#p5_p6
E21 = rtb.ET.Ry()       #reset p6_0
E22 = rtb.ET.tx(0.795)  #p6_p7
E23 = rtb.ET.tz(-0.193) #p6_p7
E24 = rtb.ET.Ry()       #reset 5_0
E25 = rtb.ET.Rz()       #5_6
E26 = rtb.ET.tx(l6)     #5_6
E27 = rtb.ET.tz(l7)     #5_6

In [12]:
irb460a = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15 * E16 * E17
irb460b = E18 * E19 * E20 * E21 * E22 * E23 * E24 * E25 * E26
irb460 = irb460a * irb460b

In [13]:
print(irb460)

tx(0.26) ⊕ tz(0.508) ⊕ tx(0.26) ⊕ tz(0.508) ⊕ tz(0.945) ⊕ tx(-0.4) ⊕ Ry(q0) ⊕ tz(0.945) ⊕ tx(1.025) ⊕ Ry(q1) ⊕ tx(-0.26) ⊕ tz(0.437) ⊕ tx(0.247) ⊕ tz(0.804) ⊕ Ry(q2) ⊕ tx(0.04884) ⊕ tz(-0.6488) ⊕ Ry(q0) ⊕ tx(-0.035) ⊕ tz(0.3337) ⊕ Ry(q1) ⊕ tx(0.795) ⊕ tz(-0.193) ⊕ Ry(q2) ⊕ Rz(q3) ⊕ tx(0.22)


## Jacobiano

O jacobiano do manipulador IRB 460 pode ser encontrado por meio de funções próprias do RTB.
Estão definidas em dois pontos de referência, no chamado `world frame` e no `frame do órgão terminal`.

In [14]:
q = np.array([0, -0.3, 0, -2.2, 0, 2, 0.79])
# Note: The irb460 object which we have been using is an instance of the ETS class

# Calculate the world frame Jacobian using the ETS class
J0 = irb460.jacob0(q)

# Calculate the end-effector frame Jacobian using the ETS class
Je = irb460.jacobe(q)

# View our Jacobians
print(f"The manipulator Jacobian (world frame) is: \n{np.round(J0, 2)}")
print(f"\nThe manipulator Jacobian (end-effector frame) is: \n{np.round(Je, 2)}")

The manipulator Jacobian (world frame) is: 
[[ 2.05  1.1  -0.08  0.52  0.22 -0.07  0.15]
 [ 0.    0.    0.   -0.    0.    0.   -0.13]
 [-1.41 -0.39 -0.76 -0.53 -0.66  0.11  0.1 ]
 [ 0.    0.    0.    0.    0.    0.   -0.56]
 [ 1.    1.    1.    1.    1.    1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.83]]

The manipulator Jacobian (end-effector frame) is: 
[[-0.53 -0.41  0.29 -0.08  0.11  0.    0.  ]
 [ 0.72  0.56 -0.4   0.11 -0.16  0.    0.22]
 [-2.32 -0.94 -0.59 -0.73 -0.67  0.13  0.  ]
 [-0.81 -0.81 -0.81 -0.81 -0.81 -0.81  0.  ]
 [-0.59 -0.59 -0.59 -0.59 -0.59 -0.59  0.  ]
 [ 0.    0.    0.    0.    0.    0.    1.  ]]
